name: klio dependency compatibility checks

on:
  schedule:
    # Run once daily
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
      - 'examples/**'
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'docs/**'
      - 'devtools/**'
      - 'examples/**'

jobs:
  core_cli_checks:
    name: "klio: verify no dependency conflicts between core/cli"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.6"
      - name: "Install dependencies"
        # pin pip version until https://github.com/pypa/pip/issues/9011 is resolved
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip==20.2.3 setuptools
      - name: "Install klio_core"
        run: |
          python -m pip install -e core --use-feature=2020-resolver
          python -m pip check
      - name: "Install klio_cli"
        run: |
          python -m pip install -e cli --use-feature=2020-resolver
          python -m pip check
  core_lib_exec_checks:
    name: "klio: verify no dependency conflicts between core/lib/exec"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "3.6"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip==20.2.3 setuptools
      - name: "Install klio_core"
        run: |
          python -m pip install -e core --use-feature=2020-resolver
          python -m pip check
      - name: "Install klio_lib"
        run: |
          python -m pip install -e lib --use-feature=2020-resolver
          python -m pip check
      - name: "Install klio_exec"
        run: |
          python -m pip install -e exec --use-feature=2020-resolver
          python -m pip check
